parameters:
#    fw1_platform.example.class: FW1\PlatformBundle\Example

services:
#    fw1_platform.example:
#        class: %fw1_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
