# src/Blogger/BlogBundle/Resources/config/routing.yml
AcmeProjectBundle_homepage:
    pattern:  /
    defaults: { _controller: AcmeProjectBundle:Page:index }
    requirements:
        _method:  GET

AcmeProjectBundle_about:
    pattern:  /about
    defaults: { _controller: AcmeProjectBundle:Page:about }
    requirements:
        _method:  GET
